### ISSUE TITLE
Tela de cadastro de motorista e passageiro

### ISSUE THREAD

**Issue by silasfabianobezerra** [elionaimelo/1driver#32]
Alinhar o icone.
![Captura de Tela 2020-07-15 às 09 56 09](https://user-images.githubusercontent.com/43277564/87547319-50fc1500-c681-11ea-9b9f-2a104a91289e.png)

Acho que da para diminuir um pouco os textos. Eu fiz isso aqui nessa página, mas pode verificar em todas as outras tá.
![Captura de Tela 2020-07-15 às 09 57 12](https://user-images.githubusercontent.com/43277564/87547423-7557f180-c681-11ea-8c81-9608c408c738.png)

**Comment by elionaimelo** [comment]
Alinha o ícone onde? Ele ta centralizado

**Comment by silasfabianobezerra** [comment]
Ele ta centralizado na imagem porque eu centralizei ele. No inspecionar eu retirei o margin-left: -20px

**Comment by elionaimelo** [comment]
Estranho, pq aqui no meu ta ok

![image](https://user-images.githubusercontent.com/4874825/87589647-ee743a80-c6bb-11ea-8c2b-4c2c38e3ff4b.png)
